# Generated by Django 4.2.10 on 2024-02-26 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workplace_violation_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonReportInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField()),
                ('report_text', models.TextField()),
                ('report_image', models.ImageField(upload_to='')),
            ],
        ),
    ]
