# Generated by Django 4.2.10 on 2024-02-22 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workplace_violation_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='google_auth_token',
            field=models.CharField(default='', max_length=100),
        ),
    ]
