# Generated by Django 4.2.10 on 2024-03-04 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workplace_violation_app', '0002_anonreportinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anonreportinfo',
            name='report_image',
        ),
        migrations.AddField(
            model_name='anonreportinfo',
            name='report_file',
            field=models.FileField(default=None, upload_to=''),
            preserve_default=False,
        ),
    ]
