# Generated by Django 4.2.10 on 2024-03-06 19:29

from django.db import migrations, models
import workplace_violation_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('workplace_violation_app', '0003_remove_anonreportinfo_report_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonreportinfo',
            name='report_file',
            field=models.FileField(storage=workplace_violation_app.models.CustomS3Storage(), upload_to=''),
        ),
    ]
