# Generated by Django 4.2.10 on 2024-03-19 23:59

from django.db import migrations, models
import workplace_violation_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('workplace_violation_app', '0004_alter_anonreportinfo_report_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField()),
                ('report_text', models.TextField()),
                ('report_file', models.FileField(storage=workplace_violation_app.models.CustomS3Storage(), upload_to='')),
                ('is_seen', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='AnonReportInfo',
        ),
    ]
