# Generated by Django 4.2.10 on 2024-03-21 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workplace_violation_app', '0006_report_report_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='report_status',
            field=models.CharField(default='New', max_length=100),
        ),
    ]
