# Generated by Django 4.2.10 on 2024-03-21 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workplace_violation_app', '0007_report_report_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='id',
        ),
        migrations.AddField(
            model_name='report',
            name='report_number',
            field=models.UUIDField(default=1, primary_key=True, serialize=False),
        ),
    ]
