# Generated by Django 4.2.10 on 2024-03-21 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workplace_violation_app', '0010_alter_report_report_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_text',
            field=models.TextField(null=True),
        ),
    ]
