# Generated by Django 4.2.10 on 2024-03-25 18:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('workplace_violation_app', '0011_alter_report_report_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='admin_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_number',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
